name: Linux Commands
on:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Run Linux Commands
        run: |
          pwd
          ls -la
          whoami
          date
          uname -a
