name: File Operations
on:
  push:

jobs:
  files:
    runs-on: ubuntu-latest

    steps:
      - name: Create and Read Files
        run: |
          mkdir test_folder
          cd test_folder
          echo "Hello Linux" > file.txt
          cat file.txt
          ls -l
        
    
